# Generated by Django 5.0.4 on 2024-05-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_text_audio_text_file_text_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='text',
            name='file',
        ),
        migrations.RemoveField(
            model_name='text',
            name='picture',
        ),
    ]
