# Generated by Django 5.0.4 on 2024-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_telegramfile_remove_text_audio_remove_text_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
